Repository wazuh/wazuh-docker, pull requests merged in 2019-05, with the labels that each got.

#164 Include protocol and port in LOGSTASH_OUTPUT environment variable
  logstash/config/entrypoint.sh
Labels: elastic_stack, enhancement

#169 Removing log files from Wazuh image
  wazuh/Dockerfile
Labels: enhancement

#178 Allow port change for elasticsearch url in kibana
  kibana/config/kibana_settings.sh
Labels: enhancement, operations
