Repository wazuh/wazuh-docker, pull requests merged in 2019-07, with the labels that each got.

#188 Wazuh image improvements
  wazuh/Dockerfile
  wazuh/config/00-wazuh.sh
  wazuh/config/data_dirs.env
  wazuh/config/entrypoint.sh
  wazuh/config/init.bash
  wazuh/config/permanent_data.env
  wazuh/config/permanent_data.sh
  wazuh/config/wazuh-api.runit.service
  wazuh/config/wazuh.runit.service
Labels: enhancement

#203 New volumes declaration in Wazuh Dockerfile
  wazuh/Dockerfile
  wazuh/config/permanent_data.env
  wazuh/config/permanent_data.sh
Labels: enhancement

#213 Fixed duplicated cluster configuration
  docker-compose.yml
  elasticsearch/Dockerfile
  elasticsearch/config/config_cluster.sh
Labels: elastic_stack

#218 Adapt Kibana image to v7.2.0
  kibana/Dockerfile
  kibana/config/kibana_settings.sh
Labels: elastic_stack, enhancement

#220 Added OSS images and deleting every XPACK occurrence
  CHANGELOG.md
  docker-compose.yml
  elasticsearch/Dockerfile
  elasticsearch/config/entrypoint.sh
  elasticsearch/config/load_settings.sh
  kibana/Dockerfile
  kibana/config/entrypoint.sh
  kibana/config/kibana_settings.sh
  kibana/config/wazuh_app_config.sh
  kibana/config/xpack_config.sh
  wazuh/Dockerfile
Labels: elastic_stack
