Repository wazuh/wazuh-docker, pull requests merged in 2021-09, with the labels that each got.

#509 Fix 4.2 upgrade
  wazuh-odfe/config/etc/cont-init.d/0-wazuh-init
  wazuh-odfe/config/permanent_data.env
Labels: upgrade

#488 Adapt cloud to v4.2.1
  wazuh/Dockerfile
  wazuh/config/01-wazuh.sh
  wazuh/config/85-save_wazuh_version.sh
  wazuh/config/permanent_data.env
Labels: status/on-hold

#522 Make utils.py file persistent when using volumes
  wazuh-odfe/config/permanent_data.env
Labels: operations
